apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  namespace: visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
          name: metabase
        env:
        - name: MB_DB_TYPE
          value: "postgres"
        - name: MB_DB_DBNAME
          value: "metabase"
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: "postgres"
        - name: MB_DB_PASS
          value: "postgres"
        - name: MB_DB_HOST
          value: "postgres.storage.svc.cluster.local"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: visualization
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30004
  selector:
    app: metabase
